server:
    port: 8880
    servlet:
        context-path: /
spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                temp:
                    use_jdbs_metadata_defaults: false
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: root